import { Fragment, type ReactNode } from 'react'
import schema from '@/data/reference/schema.json'
import { H2 } from './Heading'

/**
 * Renders the autogenerated asset-codec schema (src/data/reference/schema.json, produced server-side
 * by SchemaDocWriter walking each authorable type's static CODEC) into per-type field tables.
 *
 * Nested inline groups are flattened into one table per root type using dotted paths
 * (Camera.Offset.X); a field whose type is another root type is rendered as an on-page anchor link
 * to that type's own section, so a ref never expands inline (it is documented once, where it lives).
 */

type SchemaField = {
  key?: string
  required?: boolean
  documentation?: string
  type: 'string' | 'boolean' | 'double' | 'integer' | 'long' | 'map' | 'object' | 'array'
  of?: SchemaField
  fields?: SchemaField[]
  nestedType?: string
  ref?: string
}

type SchemaDoc = {
  generatedFrom: string
  rootTypes: string[]
  types: Record<string, { fields: SchemaField[] }>
}

const doc = schema as SchemaDoc

/** Stable on-page anchor for a root type name. */
function anchorOf(typeName: string): string {
  return typeName.toLowerCase()
}

/** A field's rendered type cell. A ref becomes a link to that type's own section. */
function typeLabel(field: SchemaField): ReactNode {
  switch (field.type) {
    case 'string':
    case 'boolean':
    case 'double':
    case 'integer':
    case 'long':
      return <code>{field.type}</code>
    case 'object':
      if (field.ref) {
        return (
          <a href={`#${anchorOf(field.ref)}`}>
            <code>{field.ref}</code>
          </a>
        )
      }
      return <code>{field.nestedType ?? 'object'}</code>
    case 'map':
      return (
        <>
          map&lt;string, {field.of ? typeLabel(field.of) : <code>any</code>}&gt;
        </>
      )
    case 'array':
      return <>{field.of ? typeLabel(field.of) : <code>any</code>}[]</>
    default:
      return <code>object</code>
  }
}

type Row = { path: string; type: ReactNode; required: boolean; doc?: string }

/** Push a row for one field, then recurse into any inline (non-ref) nested group it wraps. */
function flatten(field: SchemaField, path: string, out: Row[]): void {
  out.push({
    path,
    type: typeLabel(field),
    required: field.required ?? false,
    doc: field.documentation,
  })
  // Unwrap array/map wrappers to reach an inline object element, tracking the path prefix.
  let inner = field
  let prefix = path
  while ((inner.type === 'array' || inner.type === 'map') && inner.of) {
    prefix = inner.type === 'array' ? `${prefix}[]` : `${prefix}[*]`
    inner = inner.of
  }
  // A ref is documented under its own type section - never expanded here.
  if (inner.type === 'object' && inner.fields && !inner.ref) {
    for (const child of inner.fields) {
      flatten(child, `${prefix}.${child.key ?? '?'}`, out)
    }
  }
}

function TypeSection({ name }: { name: string }) {
  const entry = doc.types[name]
  const rows: Row[] = []
  for (const field of entry.fields) {
    flatten(field, field.key ?? '?', rows)
  }
  return (
    <section>
      <H2 id={anchorOf(name)}>{name}</H2>
      <div className="overflow-x-auto">
        <table>
          <thead>
            <tr>
              <th>Field</th>
              <th>Type</th>
              <th>Required</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={`${row.path}-${i}`}>
                <td>
                  <code>{row.path}</code>
                </td>
                <td>{row.type}</td>
                <td>{row.required ? 'yes' : ''}</td>
                <td>{row.doc ? renderDoc(row.doc) : ''}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  )
}

/** The codec docs carry lightweight **bold** markers; render them as <strong> and keep newlines. */
function renderDoc(text: string): ReactNode {
  const paragraphs = text.split('\n').filter((line) => line.trim().length > 0)
  return paragraphs.map((para, pi) => {
    const parts = para.split(/\*\*(.+?)\*\*/g)
    return (
      <span key={pi} style={{ display: 'block' }}>
        {parts.map((part, i) =>
          i % 2 === 1 ? <strong key={i}>{part}</strong> : <Fragment key={i}>{part}</Fragment>
        )}
      </span>
    )
  })
}

export function SchemaTypeIndex() {
  return (
    <div className="flex flex-wrap gap-2">
      {doc.rootTypes.map((name) => (
        <a
          key={name}
          href={`#${anchorOf(name)}`}
          className="text-sm px-2 py-1 rounded bg-dark-800 text-primary-400 hover:text-primary-300 no-underline"
        >
          {name}
        </a>
      ))}
    </div>
  )
}

export function SchemaTables() {
  return (
    <>
      {doc.rootTypes.map((name) => (
        <TypeSection key={name} name={name} />
      ))}
    </>
  )
}

export const schemaGeneratedFrom = doc.generatedFrom
