import { Metadata } from 'next'
import { DocPage } from '@/components/DocPage'
import { SchemaTables, SchemaTypeIndex, schemaGeneratedFrom } from '@/components/SchemaTables'

export const metadata: Metadata = {
  title: 'Schema Reference',
  description: 'Autogenerated field tables for every RPG Stations asset type, walked from the live codecs.',
  openGraph: {
    title: 'Schema Reference | RPG Stations Docs',
    description: 'Field-by-field tables for every authorable RPG Stations asset type, generated from each type\'s codec.',
  },
}

export default function SchemaReferencePage() {
  return (
    <DocPage
      title="Schema Reference"
      description="Field tables for every authorable asset type, generated directly from each type's codec"
      breadcrumbs={[{ title: 'Schema Reference' }]}
    >
      <p>
        Every piece of RPG Stations content is a structured Pattern-A asset: the codec IS the schema, so
        there is exactly one authority for each type&apos;s field shape. The tables below are{' '}
        <strong>generated</strong> from those codecs (<code>{schemaGeneratedFrom}</code>), so they never
        drift from what the running server actually decodes. Regenerating them is a build step, not a hand
        edit.
      </p>
      <p>
        Inline field groups are flattened into dotted paths (<code>Camera.Offset.X</code>); a{' '}
        <code>[]</code> suffix marks an array element and <code>[*]</code> a map value. When a field&apos;s
        type is another asset type, its cell links to that type&apos;s own section rather than repeating its
        fields. Every field is <strong>optional unless the Required column says otherwise</strong> - a
        partial owner override or a native <code>Parent</code> merge changes only the keys it names.
      </p>

      <SchemaTypeIndex />

      <SchemaTables />
    </DocPage>
  )
}
